import test from 'node:test';
import assert from 'node:assert/strict';
import { Pool } from 'pg';
import { copySchemaData } from '../../../deploy/scripts/supabase-branch.mjs';

const databaseUrl = process.env.BRAI_TEST_DATABASE_URL?.trim();

test('preview production copy rolls back partial data and blocks concurrent writers', {
  skip: databaseUrl ? false : 'BRAI_TEST_DATABASE_URL is required'
}, async () => {
  const suffix = `${process.pid}_${Date.now()}_${Math.random().toString(16).slice(2)}`.replace(/[^a-zA-Z0-9_]/g, '_');
  const sourceSchema = `brai_copy_source_${suffix}`;
  const targetSchema = `brai_copy_target_${suffix}`;
  const pool = new Pool({ connectionString: databaseUrl, max: 4 });
  try {
    await pool.query(`CREATE SCHEMA ${quote(sourceSchema)}`);
    await pool.query(`CREATE SCHEMA ${quote(targetSchema)}`);
    for (const schema of [sourceSchema, targetSchema]) {
      await pool.query(`
        CREATE TABLE ${qualified(schema, 'sample')} (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          value text NOT NULL
        )
      `);
    }
    await pool.query(`
      INSERT INTO ${qualified(sourceSchema, 'sample')} (id, value)
      OVERRIDING SYSTEM VALUE VALUES (7, 'source')
    `);
    await pool.query(`
      INSERT INTO ${qualified(targetSchema, 'sample')} (id, value)
      OVERRIDING SYSTEM VALUE VALUES (42, 'sentinel')
    `);
    const sequence = (await pool.query(`
      SELECT pg_get_serial_sequence($1, 'id') AS name
    `, [`${targetSchema}.sample`])).rows[0].name;
    await pool.query('SELECT setval($1::regclass, 100, true)', [sequence]);

    await assert.rejects(copySchemaData(pool, {
      sourceSchema,
      targetSchema,
      postSeedMigrations: [{ sql: 'SELECT 1 / 0' }]
    }), /division by zero/);
    assert.deepEqual((await pool.query(`
      SELECT id, value FROM ${qualified(targetSchema, 'sample')} ORDER BY id
    `)).rows, [{ id: 42, value: 'sentinel' }]);
    assert.deepEqual((await pool.query(`
      SELECT last_value::int, is_called FROM ${sequence}
    `)).rows[0], { last_value: 100, is_called: true });

    await pool.query(`ALTER SEQUENCE ${sequence} RESTART WITH 1`);
    const relationOid = (await pool.query('SELECT to_regclass($1)::oid AS oid', [`${targetSchema}.sample`])).rows[0].oid;
    const copy = copySchemaData(pool, {
      sourceSchema,
      targetSchema,
      postSeedMigrations: [{ sql: 'SELECT pg_sleep(1)' }]
    });
    await waitForLock(pool, relationOid);

    const writer = await pool.connect();
    try {
      await writer.query('BEGIN');
      await writer.query("SET LOCAL lock_timeout = '100ms'");
      await assert.rejects(
        writer.query(`INSERT INTO ${qualified(targetSchema, 'sample')} (value) VALUES ('concurrent')`),
        /lock timeout/
      );
      await writer.query('ROLLBACK');
    } finally {
      writer.release();
    }
    await copy;

    assert.deepEqual((await pool.query(`
      SELECT id, value FROM ${qualified(targetSchema, 'sample')} ORDER BY id
    `)).rows, [{ id: 7, value: 'source' }]);
    assert.deepEqual((await pool.query(`
      INSERT INTO ${qualified(targetSchema, 'sample')} (value)
      VALUES ('after-copy')
      RETURNING id, value
    `)).rows[0], { id: 8, value: 'after-copy' });
  } finally {
    await pool.query(`DROP SCHEMA IF EXISTS ${quote(targetSchema)} CASCADE`).catch(() => {});
    await pool.query(`DROP SCHEMA IF EXISTS ${quote(sourceSchema)} CASCADE`).catch(() => {});
    await pool.end();
  }
});

async function waitForLock(pool, relationOid) {
  const started = Date.now();
  while (Date.now() - started < 3000) {
    const locked = await pool.query(`
      SELECT 1
      FROM pg_locks
      WHERE relation = $1
        AND mode = 'AccessExclusiveLock'
        AND granted
      LIMIT 1
    `, [relationOid]);
    if (locked.rows.length > 0) return;
    await new Promise((resolve) => setTimeout(resolve, 20));
  }
  assert.fail('copy transaction did not acquire its target table lock');
}

function quote(value) {
  return `"${String(value).replaceAll('"', '""')}"`;
}

function qualified(schema, table) {
  return `${quote(schema)}.${quote(table)}`;
}
