import assert from "node:assert/strict";
import pg from "pg";
import {
  DATABASE_URL_ENV,
  classifyTableGroup,
  listTables,
  openReadOnlyDatabase,
  quoteIdentifier,
  readColumns,
  readDatabaseView,
  readPrimaryUserId,
  readRoleContractsAdmin,
  readTableDescriptions,
  readWorkflowAdminSummary,
  resolveDatabaseUrl,
} from "../src/lib/database.js";
import { readBraiCmdAdminSummary } from "../src/lib/braiCmdSummary.js";

const { Pool } = pg;
const baseDatabaseUrl = process.env.BRAI_TEST_DATABASE_URL;
if (!baseDatabaseUrl) throw new Error("BRAI_TEST_DATABASE_URL is required for admin self-check");

const schemaName = `admin_self_check_${process.pid}_${Date.now()}`.replace(/\W/g, "_");
const setupPool = new Pool({ connectionString: baseDatabaseUrl, max: 1 });
const databaseUrl = withSearchPath(baseDatabaseUrl, schemaName);
const db = new Pool({ connectionString: databaseUrl, max: 1 });

try {
  await setupPool.query(`CREATE SCHEMA ${quoteIdentifier(schemaName)}`);
  await db.query(`
    CREATE TABLE target_table (
      id text PRIMARY KEY
    );
    CREATE TABLE regular_table (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      value text NOT NULL,
      target_id text REFERENCES target_table(id)
    );
    CREATE TABLE dated_table (
      id integer PRIMARY KEY,
      created_at_utc text NOT NULL,
      value text NOT NULL
    );
    CREATE TABLE logs (
      id integer PRIMARY KEY,
      dt text NOT NULL,
      message text NOT NULL
    );
    CREATE TABLE app_settings (
      key text PRIMARY KEY,
      value text NOT NULL,
      updated_at_utc text NOT NULL
    );
    CREATE TABLE ${quoteIdentifier('odd"table;drop')} (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      payload text
    );
    CREATE TABLE brai_cmd_settings (
      key text PRIMARY KEY,
      value text NOT NULL,
      updated_at_utc text NOT NULL
    );
    CREATE TABLE brai_cmd_access_tokens (
      id text PRIMARY KEY,
      display_name text NOT NULL,
      token_hash text NOT NULL UNIQUE,
      device_id_hash text,
      status text NOT NULL,
      source text NOT NULL,
      created_at_utc text NOT NULL,
      activated_at_utc text,
      last_used_at_utc text,
      client_version text NOT NULL DEFAULT '',
      app_package text NOT NULL DEFAULT ''
    );
    CREATE TABLE brai_cmd_usage_events (
      id text PRIMARY KEY,
      access_token_id text NOT NULL REFERENCES brai_cmd_access_tokens(id) ON DELETE CASCADE,
      created_at_utc text NOT NULL,
      success integer NOT NULL,
      error_code text NOT NULL DEFAULT '',
      audio_bytes integer NOT NULL DEFAULT 0,
      audio_duration_ms integer NOT NULL DEFAULT 0,
      provider text NOT NULL DEFAULT '',
      model text NOT NULL DEFAULT '',
      fallback_used integer NOT NULL DEFAULT 0,
      transcription_ms integer NOT NULL DEFAULT 0,
      post_processing_ms integer NOT NULL DEFAULT 0,
      total_ms integer NOT NULL DEFAULT 0,
      transcript_chars integer NOT NULL DEFAULT 0,
      client_version text NOT NULL DEFAULT ''
    );
    CREATE TABLE table_descriptions (
      table_name text PRIMARY KEY,
      title text NOT NULL,
      short_description text NOT NULL,
      long_description text NOT NULL,
      updated_at_utc text NOT NULL
    );
    CREATE TABLE item_role_types (
      id integer PRIMARY KEY,
      title_system text NOT NULL,
      title text NOT NULL
    );
    CREATE TABLE workflow_definitions (
      id text NOT NULL,
      version integer NOT NULL,
      title text NOT NULL,
      description text NOT NULL,
      status text NOT NULL,
      task_queue text NOT NULL,
      steps_json text NOT NULL,
      diagram_mermaid text NOT NULL,
      input_schema_version text NOT NULL,
      input_schema_json text NOT NULL,
      output_schema_version text NOT NULL,
      output_schema_json text NOT NULL,
      updated_at_utc text NOT NULL,
      PRIMARY KEY (id, version)
    );
    CREATE TABLE role_contracts (
      id text PRIMARY KEY,
      item_role_types_id integer NOT NULL REFERENCES item_role_types(id),
      payload_table text NOT NULL,
      link_column text NOT NULL,
      lifecycle_json text NOT NULL,
      workflow_definition_id text,
      workflow_definition_version integer,
      input_schema_version text,
      output_schema_version text,
      owner text NOT NULL,
      event_rules_json text NOT NULL,
      created_at_utc text NOT NULL,
      updated_at_utc text NOT NULL
    );
    CREATE TABLE workflow_executions (
      id integer PRIMARY KEY,
      workflow_id text NOT NULL,
      run_id text,
      workflow_definition_id text NOT NULL,
      workflow_definition_version integer NOT NULL,
      role_contract_id text NOT NULL,
      raw_record_id text NOT NULL,
      status text NOT NULL,
      current_step text NOT NULL,
      attempt_count integer NOT NULL,
      last_error text,
      started_at_utc text,
      completed_at_utc text,
      updated_at_utc text NOT NULL
    );
  `);

  for (let index = 1; index <= 55; index += 1) {
    await db.query("INSERT INTO regular_table (value) VALUES ($1)", [`row-${index}`]);
  }
  await db.query("INSERT INTO dated_table (id, created_at_utc, value) VALUES (1, '2026-01-01T00:00:00.000Z', 'old')");
  await db.query("INSERT INTO dated_table (id, created_at_utc, value) VALUES (2, '2026-01-03T00:00:00.000Z', 'new')");
  await db.query("INSERT INTO dated_table (id, created_at_utc, value) VALUES (3, '2026-01-02T00:00:00.000Z', 'middle')");
  await db.query("INSERT INTO logs (id, dt, message) VALUES (10, '2026-01-02T00:00:00.000Z', 'middle')");
  await db.query("INSERT INTO logs (id, dt, message) VALUES (20, '2026-01-03T00:00:00.000Z', 'new')");
  await db.query("INSERT INTO logs (id, dt, message) VALUES (30, '2026-01-01T00:00:00.000Z', 'old')");
  await db.query("INSERT INTO app_settings (key, value, updated_at_utc) VALUES ('primary_user_id', 'user-1', '2026-01-01T00:00:00.000Z')");
  await db.query(`INSERT INTO ${quoteIdentifier('odd"table;drop')} (payload) VALUES ($1)`, ["safe"]);
  await db.query("INSERT INTO brai_cmd_settings (key, value, updated_at_utc) VALUES ('registration_enabled', 'false', '2026-01-01T00:00:00.000Z')");
  await db.query(`
    INSERT INTO brai_cmd_access_tokens (
      id, display_name, token_hash, device_id_hash, status, source,
      created_at_utc, activated_at_utc, last_used_at_utc, client_version, app_package
    ) VALUES
      ('token-1', 'Demo', 'hash-1', 'device-1', 'active', 'self_service', '2026-01-01T00:00:00.000Z', '2026-01-01T00:05:00.000Z', '2026-01-03T00:00:00.000Z', '42', 'world.brightos.brai'),
      ('token-2', 'Retired', 'hash-2', NULL, 'revoked', 'admin', '2026-01-02T00:00:00.000Z', NULL, NULL, '', '')
  `);
  await db.query(`
    INSERT INTO brai_cmd_usage_events (
      id, access_token_id, created_at_utc, success, error_code, audio_bytes, audio_duration_ms,
      provider, model, fallback_used, transcription_ms, post_processing_ms, total_ms, transcript_chars, client_version
    ) VALUES
      ('usage-1', 'token-1', '2026-01-03T01:00:00.000Z', 1, '', 1024, 1500, 'groq', 'whisper', 0, 800, 100, 900, 12, '42'),
      ('usage-2', 'token-1', '2026-01-03T02:00:00.000Z', 0, 'timeout', 2048, 2500, 'openai', 'gpt-4o-mini-transcribe', 1, 1600, 0, 1600, 0, '42')
  `);
  await db.query(
    `
      INSERT INTO table_descriptions (table_name, title, short_description, long_description, updated_at_utc)
      VALUES ($1, $2, $3, $4, '2026-01-01T00:00:00.000Z')
    `,
    ["regular_table", "Обычная", "Коротко.", "Длинное описание."],
  );
  await db.query(
    `
      INSERT INTO table_descriptions (table_name, title, short_description, long_description, updated_at_utc)
      VALUES ($1, $2, $3, $4, '2026-01-01T00:00:00.000Z')
    `,
    ["target_table", "Цель", "Коротко.", "Длинное описание."],
  );
  await db.query("INSERT INTO item_role_types (id, title_system, title) VALUES (2, 'inbox', 'Inbox')");
  await db.query(`
    INSERT INTO workflow_definitions (
      id, version, title, description, status, task_queue, steps_json, diagram_mermaid,
      input_schema_version, input_schema_json, output_schema_version, output_schema_json, updated_at_utc
    ) VALUES (
      'inbox.raw-normalization', 1, 'Inbox normalization', '', 'active', 'brai-inbox-normalization',
      '["ingest","raw_normalizer","apply_normalized_raw"]', 'flowchart LR; ingest --> apply',
      'input.v1', '{}', 'output.v1', '{}', '2026-01-03T00:00:00.000Z'
    )
  `);
  await db.query(`
    INSERT INTO role_contracts (
      id, item_role_types_id, payload_table, link_column, lifecycle_json,
      workflow_definition_id, workflow_definition_version, input_schema_version,
      output_schema_version, owner, event_rules_json, created_at_utc, updated_at_utc
    ) VALUES (
      'inbox', 2, 'inbox', 'item_roles_id', '{}', 'inbox.raw-normalization', 1,
      'input.v1', 'output.v1', 'brai-inbox', '{}', '2026-01-03T00:00:00.000Z', '2026-01-03T00:00:00.000Z'
    )
  `);
  await db.query(`
    INSERT INTO workflow_executions (
      id, workflow_id, run_id, workflow_definition_id, workflow_definition_version,
      role_contract_id, raw_record_id, status, current_step, attempt_count, updated_at_utc
    ) VALUES (
      1, 'brai:inbox:test', 'run-test', 'inbox.raw-normalization', 1,
      'inbox', 'inbox-test', 'running', 'raw_normalizer', 1, '2026-01-03T00:00:00.000Z'
    )
  `);

  const readOnly = openReadOnlyDatabase(databaseUrl);
  try {
    const tables = await listTables(readOnly);
    assert(tables.some((table) => table.name === "regular_table"), "regular table appears in menu");
    assert.equal(tables.find((table) => table.name === "table_descriptions").group, "system", "system table group is attached");
    assert.equal(tables.find((table) => table.name === "logs").group, "system", "logs table group is system");
    assert(tables.some((table) => table.name === 'odd"table;drop'), "dangerous table name appears in menu");
    assert.equal((await readColumns(readOnly, "regular_table")).length, 3, "columns are read through information_schema");
    assert.equal((await readTableDescriptions(readOnly)).get("regular_table").title, "Обычная", "table descriptions are readable");
  } finally {
    await readOnly.close();
  }

  const pageOne = await readDatabaseView({ databaseUrl, tableName: "regular_table", page: 1 });
  assert.equal(pageOne.rows.length, 50, "first page is limited to 50 rows");
  assert.equal(pageOne.rows[0].id, 55, "numeric id sorts descending by default");
  assert.equal(pageOne.pageCount, 2, "page count reflects remaining rows");
  assert.equal(pageOne.tableDescription.title, "Обычная", "selected table description is attached");
  assert.equal(pageOne.foreignKeys[0].targetTitle, "Цель", "foreign key target title is attached");

  const pageTwo = await readDatabaseView({ databaseUrl, tableName: "regular_table", page: 2 });
  assert.equal(pageTwo.rows.length, 5, "second page contains remaining rows");

  const idAscending = await readDatabaseView({ databaseUrl, tableName: "regular_table", page: 1, sortDirection: "asc" });
  assert.equal(idAscending.rows[0].id, 1, "numeric id sort can be reversed");

  const dated = await readDatabaseView({ databaseUrl, tableName: "dated_table", page: 1 });
  assert.deepEqual(dated.rows.map((row) => row.id), [2, 3, 1], "creation date sorts before numeric id");

  const datedAscending = await readDatabaseView({ databaseUrl, tableName: "dated_table", page: 1, sortDirection: "asc" });
  assert.deepEqual(datedAscending.rows.map((row) => row.id), [1, 3, 2], "creation date sort can be reversed");

  const logs = await readDatabaseView({ databaseUrl, tableName: "logs", page: 1 });
  assert.deepEqual(logs.rows.map((row) => row.message), ["new", "middle", "old"], "logs table sorts by dt");

  const target = await readDatabaseView({ databaseUrl, tableName: "target_table", page: 1 });
  assert.equal(target.referencedBy[0].sourceTitle, "Обычная", "incoming foreign key source title is attached");

  const odd = await readDatabaseView({ databaseUrl, tableName: 'odd"table;drop', page: 1 });
  assert.equal(odd.rows[0].payload, "safe", "quoted identifier protects odd table names");
  assert.equal(await readPrimaryUserId(databaseUrl), "user-1", "primary user id is readable for admin auth gate");

  const braiCmdSummary = await readBraiCmdAdminSummary({ databaseUrl });
  assert.equal(braiCmdSummary.settings.registrationEnabled, false, "brai cmd registration state is readable");
  assert.equal(braiCmdSummary.totals.activeTokens, 1, "brai cmd active token count is aggregated");
  assert.equal(braiCmdSummary.totals.revokedTokens, 1, "brai cmd revoked token count is aggregated");
  assert.equal(braiCmdSummary.totals.requests, 2, "brai cmd request total is aggregated");
  assert.equal(braiCmdSummary.totals.errors, 1, "brai cmd error total is aggregated");
  assert.equal(braiCmdSummary.tokens[0].displayName, "Retired", "brai cmd tokens sort by creation date desc");
  assert.equal(braiCmdSummary.tokens[1].usage.requests, 2, "brai cmd usage rolls up per token");
  assert.equal(braiCmdSummary.recentUsage[0].errorCode, "timeout", "recent brai cmd usage sorts newest first");
  assert.equal(braiCmdSummary.recentUsage[0].fallbackUsed, true, "recent brai cmd fallback flag is preserved");

  const workflowSummary = await readWorkflowAdminSummary(databaseUrl);
  assert.equal(workflowSummary.definitions[0].id, "inbox.raw-normalization", "workflow definition read model is readable");
  assert.equal(workflowSummary.executions[0].current_step, "raw_normalizer", "workflow execution read model is readable");
  const roleContracts = await readRoleContractsAdmin(databaseUrl);
  assert.equal(roleContracts[0].role_key, "inbox", "role contract joins its role type");
  assert.equal(roleContracts[0].workflow_title, "Inbox normalization", "role contract joins its workflow definition");

  process.env[DATABASE_URL_ENV] = databaseUrl;
  assert.equal(resolveDatabaseUrl(), databaseUrl, "production database URL resolves");
  assert.equal(classifyTableGroup("app_settings"), "user", "app settings are user data");
  assert.equal(classifyTableGroup("focus_session_versions"), "user", "focus session versions are user data");
  assert.equal(classifyTableGroup("items"), "system", "items registry is system data");
  assert.equal(classifyTableGroup("logs"), "system", "runtime logs are system data");
} finally {
  await db.end().catch(() => {});
  await setupPool.query(`DROP SCHEMA IF EXISTS ${quoteIdentifier(schemaName)} CASCADE`).catch(() => {});
  await setupPool.end().catch(() => {});
}

console.log("admin db self-check passed");

function withSearchPath(databaseUrl, schemaName) {
  const url = new URL(databaseUrl);
  const existing = url.searchParams.get("options");
  url.searchParams.set("options", [existing, `-c search_path=${schemaName}`].filter(Boolean).join(" "));
  return url.toString();
}
