import assert from "node:assert/strict";
import pg from "pg";
import {
  DATABASE_URL_ENV,
  classifyTableGroup,
  listTables,
  openReadOnlyDatabase,
  quoteIdentifier,
  readColumns,
  readDatabaseView,
  readTableDescriptions,
  resolveDatabaseUrl,
} from "../src/lib/database.js";

const { Pool } = pg;
const baseDatabaseUrl = process.env.BRAI_TEST_DATABASE_URL;
if (!baseDatabaseUrl) throw new Error("BRAI_TEST_DATABASE_URL is required for admin self-check");

const schemaName = `admin_self_check_${process.pid}_${Date.now()}`.replace(/\W/g, "_");
const setupPool = new Pool({ connectionString: baseDatabaseUrl, max: 1 });
const databaseUrl = withSearchPath(baseDatabaseUrl, schemaName);
const db = new Pool({ connectionString: databaseUrl, max: 1 });

try {
  await setupPool.query(`CREATE SCHEMA ${quoteIdentifier(schemaName)}`);
  await db.query(`
    CREATE TABLE target_table (
      id text PRIMARY KEY
    );
    CREATE TABLE regular_table (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      value text NOT NULL,
      target_id text REFERENCES target_table(id)
    );
    CREATE TABLE dated_table (
      id integer PRIMARY KEY,
      created_at_utc text NOT NULL,
      value text NOT NULL
    );
    CREATE TABLE logs (
      id integer PRIMARY KEY,
      dt text NOT NULL,
      message text NOT NULL
    );
    CREATE TABLE ${quoteIdentifier('odd"table;drop')} (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      payload text
    );
    CREATE TABLE table_descriptions (
      table_name text PRIMARY KEY,
      title text NOT NULL,
      short_description text NOT NULL,
      long_description text NOT NULL,
      updated_at_utc text NOT NULL
    );
  `);

  for (let index = 1; index <= 55; index += 1) {
    await db.query("INSERT INTO regular_table (value) VALUES ($1)", [`row-${index}`]);
  }
  await db.query("INSERT INTO dated_table (id, created_at_utc, value) VALUES (1, '2026-01-01T00:00:00.000Z', 'old')");
  await db.query("INSERT INTO dated_table (id, created_at_utc, value) VALUES (2, '2026-01-03T00:00:00.000Z', 'new')");
  await db.query("INSERT INTO dated_table (id, created_at_utc, value) VALUES (3, '2026-01-02T00:00:00.000Z', 'middle')");
  await db.query("INSERT INTO logs (id, dt, message) VALUES (10, '2026-01-02T00:00:00.000Z', 'middle')");
  await db.query("INSERT INTO logs (id, dt, message) VALUES (20, '2026-01-03T00:00:00.000Z', 'new')");
  await db.query("INSERT INTO logs (id, dt, message) VALUES (30, '2026-01-01T00:00:00.000Z', 'old')");
  await db.query(`INSERT INTO ${quoteIdentifier('odd"table;drop')} (payload) VALUES ($1)`, ["safe"]);
  await db.query(
    `
      INSERT INTO table_descriptions (table_name, title, short_description, long_description, updated_at_utc)
      VALUES ($1, $2, $3, $4, '2026-01-01T00:00:00.000Z')
    `,
    ["regular_table", "Обычная", "Коротко.", "Длинное описание."],
  );
  await db.query(
    `
      INSERT INTO table_descriptions (table_name, title, short_description, long_description, updated_at_utc)
      VALUES ($1, $2, $3, $4, '2026-01-01T00:00:00.000Z')
    `,
    ["target_table", "Цель", "Коротко.", "Длинное описание."],
  );

  const readOnly = openReadOnlyDatabase(databaseUrl);
  try {
    const tables = await listTables(readOnly);
    assert(tables.some((table) => table.name === "regular_table"), "regular table appears in menu");
    assert.equal(tables.find((table) => table.name === "table_descriptions").group, "system", "system table group is attached");
    assert.equal(tables.find((table) => table.name === "logs").group, "system", "logs table group is system");
    assert(tables.some((table) => table.name === 'odd"table;drop'), "dangerous table name appears in menu");
    assert.equal((await readColumns(readOnly, "regular_table")).length, 3, "columns are read through information_schema");
    assert.equal((await readTableDescriptions(readOnly)).get("regular_table").title, "Обычная", "table descriptions are readable");
  } finally {
    await readOnly.close();
  }

  const pageOne = await readDatabaseView({ databaseUrl, tableName: "regular_table", page: 1 });
  assert.equal(pageOne.rows.length, 50, "first page is limited to 50 rows");
  assert.equal(pageOne.rows[0].id, 55, "numeric id sorts descending by default");
  assert.equal(pageOne.pageCount, 2, "page count reflects remaining rows");
  assert.equal(pageOne.tableDescription.title, "Обычная", "selected table description is attached");
  assert.equal(pageOne.foreignKeys[0].targetTitle, "Цель", "foreign key target title is attached");

  const pageTwo = await readDatabaseView({ databaseUrl, tableName: "regular_table", page: 2 });
  assert.equal(pageTwo.rows.length, 5, "second page contains remaining rows");

  const idAscending = await readDatabaseView({ databaseUrl, tableName: "regular_table", page: 1, sortDirection: "asc" });
  assert.equal(idAscending.rows[0].id, 1, "numeric id sort can be reversed");

  const dated = await readDatabaseView({ databaseUrl, tableName: "dated_table", page: 1 });
  assert.deepEqual(dated.rows.map((row) => row.id), [2, 3, 1], "creation date sorts before numeric id");

  const datedAscending = await readDatabaseView({ databaseUrl, tableName: "dated_table", page: 1, sortDirection: "asc" });
  assert.deepEqual(datedAscending.rows.map((row) => row.id), [1, 3, 2], "creation date sort can be reversed");

  const logs = await readDatabaseView({ databaseUrl, tableName: "logs", page: 1 });
  assert.deepEqual(logs.rows.map((row) => row.message), ["new", "middle", "old"], "logs table sorts by dt");

  const target = await readDatabaseView({ databaseUrl, tableName: "target_table", page: 1 });
  assert.equal(target.referencedBy[0].sourceTitle, "Обычная", "incoming foreign key source title is attached");

  const odd = await readDatabaseView({ databaseUrl, tableName: 'odd"table;drop', page: 1 });
  assert.equal(odd.rows[0].payload, "safe", "quoted identifier protects odd table names");

  process.env[DATABASE_URL_ENV] = databaseUrl;
  assert.equal(resolveDatabaseUrl(), databaseUrl, "production database URL resolves");
  assert.equal(classifyTableGroup("app_settings"), "user", "app settings are user data");
  assert.equal(classifyTableGroup("focus_session_versions"), "user", "focus session versions are user data");
  assert.equal(classifyTableGroup("items"), "system", "items registry is system data");
  assert.equal(classifyTableGroup("logs"), "system", "runtime logs are system data");
} finally {
  await db.end().catch(() => {});
  await setupPool.query(`DROP SCHEMA IF EXISTS ${quoteIdentifier(schemaName)} CASCADE`).catch(() => {});
  await setupPool.end().catch(() => {});
}

console.log("admin db self-check passed");

function withSearchPath(databaseUrl, schemaName) {
  const url = new URL(databaseUrl);
  const existing = url.searchParams.get("options");
  url.searchParams.set("options", [existing, `-c search_path=${schemaName}`].filter(Boolean).join(" "));
  return url.toString();
}
