ALTER TABLE focus_session_intervals DROP CONSTRAINT IF EXISTS focus_session_intervals_created_event_id_fkey;
ALTER TABLE focus_session_intervals DROP CONSTRAINT IF EXISTS focus_session_intervals_ended_event_id_fkey;
ALTER TABLE focus_session_sources DROP CONSTRAINT IF EXISTS focus_session_sources_event_id_fkey;

CREATE TABLE IF NOT EXISTS events (
  id text PRIMARY KEY,
  event_domain text NOT NULL CHECK (event_domain IN ('timer', 'activity', 'inbox', 'system')),
  event_id text NOT NULL,
  event_type text NOT NULL,
  event_action text NOT NULL,
  title text NOT NULL,
  items_id text REFERENCES items(id),
  subject_type text NOT NULL,
  subject_id text,
  actor_type text NOT NULL DEFAULT 'user',
  actor_id text,
  device_id text REFERENCES timer_devices(device_id),
  client_sequence integer,
  server_sequence integer NOT NULL UNIQUE,
  domain_sequence integer NOT NULL,
  status text NOT NULL DEFAULT 'accepted' CHECK (status IN ('accepted', 'ignored')),
  ignore_reason text,
  occurred_at_utc text NOT NULL,
  received_at_utc text NOT NULL,
  base_server_revision integer,
  payload_version integer NOT NULL DEFAULT 1,
  payload_json text NOT NULL DEFAULT '{}',
  trace_id text,
  created_at_utc text NOT NULL,
  user_id text,
  UNIQUE (event_domain, event_id),
  UNIQUE (event_domain, device_id, client_sequence),
  UNIQUE (event_domain, domain_sequence)
);

CREATE INDEX IF NOT EXISTS idx_events_domain_user_sequence ON events (event_domain, user_id, domain_sequence);
CREATE INDEX IF NOT EXISTS idx_events_items_occurred ON events (items_id, occurred_at_utc, server_sequence);
CREATE INDEX IF NOT EXISTS idx_events_trace ON events (trace_id);
CREATE INDEX IF NOT EXISTS idx_events_status_domain ON events (status, event_domain, occurred_at_utc);

ALTER TABLE ai_logs ADD COLUMN IF NOT EXISTS trace_id text;
CREATE INDEX IF NOT EXISTS idx_ai_logs_trace_dt ON ai_logs (trace_id, dt);

CREATE TABLE IF NOT EXISTS logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trace_id text,
  span_id text,
  parent_span_id text,
  dt text NOT NULL,
  observed_at_utc text NOT NULL,
  severity_text text NOT NULL,
  severity_number integer,
  service text NOT NULL,
  source text NOT NULL,
  operation text NOT NULL,
  status text NOT NULL CHECK (status IN ('started', 'done', 'failed', 'skipped')),
  duration_ms integer,
  user_id text,
  items_id text REFERENCES items(id),
  event_domain text,
  event_id text,
  device_id text,
  client_sequence integer,
  reason text,
  message text NOT NULL DEFAULT '',
  json_data text NOT NULL DEFAULT '{}',
  expires_at_utc text NOT NULL,
  created_at_utc text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_logs_dt ON logs (dt);
CREATE INDEX IF NOT EXISTS idx_logs_trace ON logs (trace_id, dt);
CREATE INDEX IF NOT EXISTS idx_logs_source_status_dt ON logs (source, status, dt);
CREATE INDEX IF NOT EXISTS idx_logs_event_receipt ON logs (event_domain, event_id);
CREATE INDEX IF NOT EXISTS idx_logs_device_sequence ON logs (event_domain, device_id, client_sequence);
CREATE INDEX IF NOT EXISTS idx_logs_expires ON logs (expires_at_utc);

ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE logs ENABLE ROW LEVEL SECURITY;

INSERT INTO items (id, user_id, title, description, author, created_at_utc, updated_at_utc, deleted_at_utc)
SELECT id, user_id, title, description_md, author, created_at_utc, updated_at_utc, deleted_at_utc
FROM activities
ON CONFLICT (id) DO NOTHING;

INSERT INTO items (id, user_id, title, description, author, created_at_utc, updated_at_utc, deleted_at_utc)
SELECT id, user_id, title, description_text, author, created_at_utc, updated_at_utc, deleted_at_utc
FROM inbox
ON CONFLICT (id) DO NOTHING;

INSERT INTO items (id, user_id, title, description, author, created_at_utc, updated_at_utc, deleted_at_utc)
SELECT id, user_id, 'Focus session', '', '', created_at_utc, updated_at_utc, deleted_at_utc
FROM focus_sessions
ON CONFLICT (id) DO NOTHING;

INSERT INTO item_roles (items_id, item_role_types_id, active_from_utc, active_to_utc, status, metadata_json)
SELECT a.id, 1, a.created_at_utc, NULL, CASE WHEN a.deleted_at_utc IS NULL THEN 'active' ELSE 'deleted' END, '{}'
FROM activities a
WHERE NOT EXISTS (SELECT 1 FROM item_roles r WHERE r.items_id = a.id AND r.item_role_types_id = 1);

INSERT INTO item_roles (items_id, item_role_types_id, active_from_utc, active_to_utc, status, metadata_json)
SELECT i.id, 2, i.created_at_utc, NULL, CASE WHEN i.deleted_at_utc IS NULL THEN 'active' ELSE 'deleted' END, '{}'
FROM inbox i
WHERE NOT EXISTS (SELECT 1 FROM item_roles r WHERE r.items_id = i.id AND r.item_role_types_id = 2);

INSERT INTO item_roles (items_id, item_role_types_id, active_from_utc, active_to_utc, status, metadata_json)
SELECT s.id, 3, s.created_at_utc, NULL, CASE WHEN s.deleted_at_utc IS NULL THEN 'active' ELSE 'deleted' END, '{}'
FROM focus_sessions s
WHERE NOT EXISTS (SELECT 1 FROM item_roles r WHERE r.items_id = s.id AND r.item_role_types_id = 3);

INSERT INTO events (
  id, event_domain, event_id, event_type, event_action, title, items_id, subject_type, subject_id,
  actor_type, actor_id, device_id, client_sequence, server_sequence, domain_sequence, status,
  ignore_reason, occurred_at_utc, received_at_utc, base_server_revision, payload_version, payload_json,
  created_at_utc, user_id
)
SELECT 'timer:' || event_id, 'timer', event_id, type, 'timer.' || type, 'Timer ' || type,
  NULL, 'timer', local_timer_id, CASE WHEN device_id = 'legacy-server' THEN 'system' ELSE 'user' END,
  device_id, device_id, client_sequence, server_sequence, server_sequence, status, ignore_reason,
  occurred_at_utc, received_at_utc, base_server_revision, payload_version, COALESCE(metadata_json, '{}'),
  received_at_utc, user_id
FROM timer_events
ON CONFLICT DO NOTHING;

WITH offsets AS (
  SELECT COALESCE((SELECT MAX(server_sequence) FROM timer_events), 0) AS timer_max
)
INSERT INTO events (
  id, event_domain, event_id, event_type, event_action, title, items_id, subject_type, subject_id,
  actor_type, actor_id, device_id, client_sequence, server_sequence, domain_sequence, status,
  ignore_reason, occurred_at_utc, received_at_utc, payload_version, payload_json, created_at_utc, user_id
)
SELECT 'activity:' || e.event_id, 'activity', e.event_id, e.change_type, 'activity.' || e.change_type,
  'Activity ' || e.change_type, CASE WHEN i.id IS NULL OR e.change_type = 'reorder' THEN NULL ELSE e.activity_id END,
  CASE WHEN e.change_type = 'reorder' THEN 'activity_list' ELSE 'activity' END,
  CASE WHEN e.change_type = 'reorder' THEN NULL ELSE e.activity_id END,
  'user', e.device_id, e.device_id, e.client_sequence, offsets.timer_max + e.server_sequence,
  e.server_sequence, e.status, e.ignore_reason, e.occurred_at_utc, e.received_at_utc,
  e.payload_version, COALESCE(e.payload_json, '{}'), e.received_at_utc, e.user_id
FROM activity_events e
CROSS JOIN offsets
LEFT JOIN items i ON i.id = e.activity_id
ON CONFLICT DO NOTHING;

WITH offsets AS (
  SELECT
    COALESCE((SELECT MAX(server_sequence) FROM timer_events), 0)
      + COALESCE((SELECT MAX(server_sequence) FROM activity_events), 0) AS previous_max
)
INSERT INTO events (
  id, event_domain, event_id, event_type, event_action, title, items_id, subject_type, subject_id,
  actor_type, actor_id, device_id, client_sequence, server_sequence, domain_sequence, status,
  ignore_reason, occurred_at_utc, received_at_utc, payload_version, payload_json, created_at_utc, user_id
)
SELECT 'inbox:' || e.event_id, 'inbox', e.event_id, e.type, 'inbox.' || e.type,
  'Inbox ' || e.type, CASE WHEN i.id IS NULL THEN NULL ELSE e.inbox_id END, 'inbox', e.inbox_id,
  CASE WHEN e.device_id = 'inbox-ai' THEN 'agent' ELSE 'user' END, e.device_id,
  e.device_id, e.client_sequence, offsets.previous_max + e.server_sequence, e.server_sequence,
  e.status, e.ignore_reason, e.occurred_at_utc, e.received_at_utc, e.payload_version,
  COALESCE(e.payload_json, '{}'), e.received_at_utc, e.user_id
FROM inbox_events e
CROSS JOIN offsets
LEFT JOIN items i ON i.id = e.inbox_id
ON CONFLICT DO NOTHING;

INSERT INTO logs (
  dt, observed_at_utc, severity_text, service, source, operation, status, user_id,
  event_domain, event_id, device_id, client_sequence, reason, message, json_data,
  expires_at_utc, created_at_utc
)
SELECT received_at_utc, received_at_utc, 'WARN', 'brai-api', 'sync', 'sync.event_ignored',
  'skipped', user_id, event_domain, event_id, device_id, client_sequence, ignore_reason,
  event_domain || '.' || COALESCE(ignore_reason, 'ignored'), payload_json,
  (received_at_utc::timestamptz + interval '180 days')::text, received_at_utc
FROM events e
WHERE status = 'ignored'
  AND NOT EXISTS (
    SELECT 1 FROM logs l
    WHERE l.operation = 'sync.event_ignored'
      AND l.event_domain = e.event_domain
      AND l.event_id = e.event_id
  );

INSERT INTO sequence_counters (name, last_value)
VALUES
  ('events.server_sequence', COALESCE((SELECT MAX(server_sequence) FROM events), 0)),
  ('events.domain_sequence.timer', COALESCE((SELECT MAX(domain_sequence) FROM events WHERE event_domain = 'timer'), 0)),
  ('events.domain_sequence.activity', COALESCE((SELECT MAX(domain_sequence) FROM events WHERE event_domain = 'activity'), 0)),
  ('events.domain_sequence.inbox', COALESCE((SELECT MAX(domain_sequence) FROM events WHERE event_domain = 'inbox'), 0))
ON CONFLICT (name) DO UPDATE
SET last_value = GREATEST(sequence_counters.last_value, excluded.last_value);

INSERT INTO table_descriptions (table_name, title, short_description, long_description, updated_at_utc) VALUES
  ('events', 'Global events', 'Единый canonical event log для бизнес-событий Brai.', 'Заменяет runtime-чтение timer_events, activity_events и inbox_events: accepted rows участвуют в replay/read models, ignored rows сохраняют sync idempotency и revision history.', now()::text),
  ('logs', 'Technical logs', 'Структурированные технические логи runtime-операций.', 'Хранит request/sync/scheduler/agent-invocation/deploy summaries без секретов и без AI outputs; строки имеют expires_at_utc для retention.', now()::text),
  ('ai_logs', 'AI logs', 'Отдельный журнал фактических AI-срабатываний.', 'Хранит agent inputs/outputs в json_data и trace_id для связи с logs; technical logs не дублируют AI outputs.', now()::text)
ON CONFLICT (table_name) DO UPDATE SET
  title = excluded.title,
  short_description = excluded.short_description,
  long_description = excluded.long_description,
  updated_at_utc = excluded.updated_at_utc;

INSERT INTO schema_migrations (version, applied_at_utc, description)
VALUES (50, now()::text, 'add global events and technical logs')
ON CONFLICT (version) DO NOTHING;
