-- brai:reapply-after-production-seed

CREATE TABLE IF NOT EXISTS role_statuses (
  id text PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  is_terminal integer NOT NULL DEFAULT 0 CHECK (is_terminal IN (0, 1)),
  created_at_utc text NOT NULL
);

INSERT INTO role_statuses (id, title, description, is_terminal, created_at_utc) VALUES
  ('active', 'Active', 'Роль активна и участвует в текущем состоянии сущности.', 0, now()::text),
  ('ended', 'Ended', 'Роль завершена и остается в истории сущности.', 1, now()::text),
  ('deleted', 'Deleted', 'Роль удалена и остается в истории сущности.', 1, now()::text)
ON CONFLICT (id) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  is_terminal = excluded.is_terminal;

CREATE TABLE IF NOT EXISTS workflow_definitions (
  id text NOT NULL,
  version integer NOT NULL CHECK (version > 0),
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  status text NOT NULL CHECK (status IN ('active', 'retired')),
  task_queue text NOT NULL,
  steps_json text NOT NULL DEFAULT '[]',
  diagram_mermaid text NOT NULL,
  input_schema_version text NOT NULL,
  input_schema_json text NOT NULL,
  output_schema_version text NOT NULL,
  output_schema_json text NOT NULL,
  created_at_utc text NOT NULL,
  updated_at_utc text NOT NULL,
  PRIMARY KEY (id, version)
);

CREATE TABLE IF NOT EXISTS role_contracts (
  id text PRIMARY KEY,
  item_role_types_id integer NOT NULL UNIQUE REFERENCES item_role_types(id),
  payload_table text NOT NULL,
  link_column text NOT NULL DEFAULT 'item_roles_id',
  lifecycle_json text NOT NULL DEFAULT '{}',
  workflow_definition_id text,
  workflow_definition_version integer,
  input_schema_version text,
  output_schema_version text,
  owner text NOT NULL,
  event_rules_json text NOT NULL DEFAULT '{}',
  created_at_utc text NOT NULL,
  updated_at_utc text NOT NULL,
  FOREIGN KEY (workflow_definition_id, workflow_definition_version)
    REFERENCES workflow_definitions(id, version)
);

CREATE TABLE IF NOT EXISTS workflow_executions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workflow_definition_id text NOT NULL,
  workflow_definition_version integer NOT NULL,
  workflow_id text NOT NULL UNIQUE,
  run_id text,
  role_contract_id text NOT NULL REFERENCES role_contracts(id),
  raw_record_id text NOT NULL,
  status text NOT NULL CHECK (status IN ('queued', 'running', 'completed', 'failed', 'needs_review')),
  current_step text NOT NULL,
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  last_error text,
  started_at_utc text,
  completed_at_utc text,
  created_at_utc text NOT NULL,
  updated_at_utc text NOT NULL,
  user_id text,
  FOREIGN KEY (workflow_definition_id, workflow_definition_version)
    REFERENCES workflow_definitions(id, version)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'item_roles_status_fkey'
      AND conrelid = 'item_roles'::regclass
  ) THEN
    ALTER TABLE item_roles
      ADD CONSTRAINT item_roles_status_fkey
      FOREIGN KEY (status) REFERENCES role_statuses(id);
  END IF;
END;
$$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_item_roles_one_active_type
  ON item_roles (items_id, item_role_types_id)
  WHERE status = 'active';

ALTER TABLE events ADD COLUMN IF NOT EXISTS item_roles_id integer REFERENCES item_roles(id);
ALTER TABLE activities ADD COLUMN IF NOT EXISTS item_roles_id integer REFERENCES item_roles(id);
ALTER TABLE inbox ADD COLUMN IF NOT EXISTS item_roles_id integer REFERENCES item_roles(id);
ALTER TABLE focus_sessions ADD COLUMN IF NOT EXISTS item_roles_id integer REFERENCES item_roles(id);
ALTER TABLE inbox ADD COLUMN IF NOT EXISTS initial_event_id text REFERENCES events(id);
ALTER TABLE inbox ADD COLUMN IF NOT EXISTS workflow_execution_id integer REFERENCES workflow_executions(id);
ALTER TABLE inbox ADD COLUMN IF NOT EXISTS ingest_idempotency_hash text;
ALTER TABLE inbox ADD COLUMN IF NOT EXISTS ingest_payload_hash text;

ALTER TABLE ai_logs ADD COLUMN IF NOT EXISTS workflow_id text;
ALTER TABLE ai_logs ADD COLUMN IF NOT EXISTS run_id text;
ALTER TABLE ai_logs ADD COLUMN IF NOT EXISTS attempt_number integer;

CREATE UNIQUE INDEX IF NOT EXISTS idx_inbox_ingest_idempotency
  ON inbox (ingest_idempotency_hash)
  WHERE ingest_idempotency_hash IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_inbox_raw_queue
  ON inbox (created_at_utc, id)
  WHERE item_roles_id IS NULL AND deleted_at_utc IS NULL;
CREATE INDEX IF NOT EXISTS idx_inbox_item_roles ON inbox (item_roles_id);
CREATE INDEX IF NOT EXISTS idx_activities_item_roles ON activities (item_roles_id);
CREATE INDEX IF NOT EXISTS idx_focus_sessions_item_roles ON focus_sessions (item_roles_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_inbox_initial_event ON inbox (initial_event_id)
  WHERE initial_event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_events_item_roles_occurred
  ON events (item_roles_id, occurred_at_utc, server_sequence);
CREATE INDEX IF NOT EXISTS idx_events_domain_subject_occurred
  ON events (event_domain, subject_id, status, occurred_at_utc, domain_sequence);
CREATE INDEX IF NOT EXISTS idx_workflow_executions_status_updated
  ON workflow_executions (status, updated_at_utc);
CREATE INDEX IF NOT EXISTS idx_workflow_executions_raw_record
  ON workflow_executions (role_contract_id, raw_record_id, created_at_utc);
CREATE INDEX IF NOT EXISTS idx_ai_logs_workflow_attempt
  ON ai_logs (workflow_id, attempt_number, dt);

INSERT INTO workflow_definitions (
  id, version, title, description, status, task_queue, steps_json, diagram_mermaid,
  input_schema_version, input_schema_json, output_schema_version, output_schema_json,
  created_at_utc, updated_at_utc
) VALUES (
  'inbox.raw-normalization',
  1,
  'Inbox raw normalization',
  'Создает entity и Inbox role только после schema-valid результата агентов.',
  'active',
  'brai-inbox-normalization',
  '["ingest","raw_normalizer","apply_normalized_raw"]',
  $mermaid$flowchart LR
  ingest["ingest"] --> normalizer["raw_normalizer"]
  normalizer -->|valid JSON| apply["apply_normalized_raw"]
  normalizer -->|validation error, max 3| normalizer
  normalizer -->|3 failures| review["needs_review"]
  apply --> done["completed"]$mermaid$,
  'brai.inbox.raw.v1',
  '{"type":"object","required":["inbox_id"],"properties":{"inbox_id":{"type":"string","minLength":1}},"additionalProperties":false}',
  'brai.inbox.normalized.v1',
  '{"type":"object","required":["title","description","class_key","normalization"],"properties":{"title":{"type":"string","minLength":1,"maxLength":80},"description":{"type":"string","minLength":1,"maxLength":8000},"class_key":{"type":"string","pattern":"^[a-z][a-z0-9_-]{1,62}$"},"class_title":{"type":"string","maxLength":8000},"class_description":{"type":"string","maxLength":8000},"normalization":{"type":"string","minLength":1,"maxLength":8000}},"additionalProperties":false}',
  now()::text,
  now()::text
)
ON CONFLICT (id, version) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  status = excluded.status,
  task_queue = excluded.task_queue,
  steps_json = excluded.steps_json,
  diagram_mermaid = excluded.diagram_mermaid,
  input_schema_version = excluded.input_schema_version,
  input_schema_json = excluded.input_schema_json,
  output_schema_version = excluded.output_schema_version,
  output_schema_json = excluded.output_schema_json,
  updated_at_utc = excluded.updated_at_utc;

INSERT INTO role_contracts (
  id, item_role_types_id, payload_table, link_column, lifecycle_json,
  workflow_definition_id, workflow_definition_version, input_schema_version,
  output_schema_version, owner, event_rules_json, created_at_utc, updated_at_utc
) VALUES
  (
    'activity', 1, 'activities', 'item_roles_id',
    '{"statuses":["active","ended","deleted"]}',
    NULL, NULL, NULL, NULL, 'brai-core',
    '{"link":"item_roles_id","raw_event":false}', now()::text, now()::text
  ),
  (
    'inbox', 2, 'inbox', 'item_roles_id',
    '{"statuses":["active","ended","deleted"],"raw_when":"item_roles_id is null"}',
    'inbox.raw-normalization', 1, 'brai.inbox.raw.v1', 'brai.inbox.normalized.v1', 'brai-inbox',
    '{"link":"item_roles_id","initial_event_column":"initial_event_id"}', now()::text, now()::text
  ),
  (
    'focus_session', 3, 'focus_sessions', 'item_roles_id',
    '{"statuses":["active","ended","deleted"]}',
    NULL, NULL, NULL, NULL, 'brai-core',
    '{"link":"item_roles_id","raw_event":false}', now()::text, now()::text
  )
ON CONFLICT (id) DO UPDATE SET
  item_role_types_id = excluded.item_role_types_id,
  payload_table = excluded.payload_table,
  link_column = excluded.link_column,
  lifecycle_json = excluded.lifecycle_json,
  workflow_definition_id = excluded.workflow_definition_id,
  workflow_definition_version = excluded.workflow_definition_version,
  input_schema_version = excluded.input_schema_version,
  output_schema_version = excluded.output_schema_version,
  owner = excluded.owner,
  event_rules_json = excluded.event_rules_json,
  updated_at_utc = excluded.updated_at_utc;

UPDATE activities a
SET item_roles_id = r.id
FROM item_roles r
WHERE a.item_roles_id IS NULL
  AND r.items_id = a.id
  AND r.item_role_types_id = 1;

UPDATE inbox i
SET item_roles_id = r.id
FROM item_roles r
WHERE i.item_roles_id IS NULL
  AND r.items_id = i.id
  AND r.item_role_types_id = 2;

UPDATE focus_sessions f
SET item_roles_id = r.id
FROM item_roles r
WHERE f.item_roles_id IS NULL
  AND r.items_id = f.id
  AND r.item_role_types_id = 3;

UPDATE events e
SET item_roles_id = r.id
FROM item_roles r
JOIN item_role_types rt ON rt.id = r.item_role_types_id
WHERE e.item_roles_id IS NULL
  AND r.items_id = e.items_id
  AND rt.title_system = e.subject_type;

UPDATE inbox i
SET initial_event_id = (
  SELECT e.id
  FROM events e
  WHERE e.event_domain = 'inbox'
    AND e.subject_id = i.id
    AND e.event_type = 'create'
  ORDER BY e.occurred_at_utc, e.domain_sequence
  LIMIT 1
)
WHERE i.initial_event_id IS NULL;

UPDATE agents
SET version = '2',
    interactions_description = 'Вызывается activity шага raw_normalizer workflow inbox.raw-normalization; возвращает данные скрипту и не мутирует domain tables.',
    side_effects_description = 'Пишет ровно один ai_logs на реальное выполнение; domain mutation выполняет apply_normalized_raw.',
    source_module = 'services/brai_api/src/inbox-workflow-runtime.js',
    updated_at_utc = now()::text
WHERE id IN ('inbox.image_describer', 'inbox.normalizer');

INSERT INTO table_descriptions (table_name, title, short_description, long_description, updated_at_utc) VALUES
  ('items', 'Items', 'Identity-уровень сущностей Brai.', 'Хранит стабильную identity сущности; role-specific данные и lifecycle находятся в item_roles и соответствующей role table.', now()::text),
  ('item_roles', 'Item roles', 'Связи сущностей с типами ролей и lifecycle-статусом.', 'Связывает items с item_role_types; partial unique index допускает не более одной active роли одного типа для сущности, сохраняя ended/deleted историю.', now()::text),
  ('activities', 'Activities', 'Role table пользовательских действий.', 'Role-specific данные Activity; нормализованная запись связывается с entity только через activities.item_roles_id.', now()::text),
  ('focus_sessions', 'Focus sessions', 'Role table сессий фокусировки.', 'Role-specific данные Focus session; нормализованная запись связывается с entity только через focus_sessions.item_roles_id.', now()::text),
  ('role_statuses', 'Role statuses', 'Справочник lifecycle-статусов ролей сущностей.', 'Определяет допустимые active/ended/deleted состояния item_roles и терминальность статуса.', now()::text),
  ('role_contracts', 'Role contracts', 'Контракты role tables для workflow и агентов.', 'Связывает role type, payload table, item_roles_id, lifecycle, workflow/schema versions, owner и event rules.', now()::text),
  ('workflow_definitions', 'Workflow definitions', 'Версионированный source of truth product workflows.', 'Хранит шаги, task queue, Mermaid diagram и versioned JSON schemas; Admin рендерит diagram через Kroki.', now()::text),
  ('workflow_executions', 'Workflow executions', 'Компактный read model выполнения product workflows.', 'Хранит workflow/run ids, текущий шаг, status, attempt count и bounded last error для UI/Admin без polling Temporal history.', now()::text),
  ('inbox', 'Inbox', 'Role table входящих записей с raw и normalized состояниями.', 'Raw строка не имеет item_roles_id; workflow inbox.raw-normalization создает entity/role, связывает initial_event_id и сохраняет compact execution state.', now()::text),
  ('events', 'Global events', 'Единый canonical event log для бизнес-событий Brai.', 'Role-linked события используют item_roles_id. Принятые raw Inbox events создаются без ссылки и получают item_roles_id после успешной нормализации без изменения исходного payload, timestamp или type.', now()::text),
  ('ai_logs', 'AI logs', 'Отдельный журнал фактических AI-срабатываний.', 'Каждый реальный AI call создает строку с workflow_id, run_id и attempt_number; technical logs не дублируют AI outputs.', now()::text)
ON CONFLICT (table_name) DO UPDATE SET
  title = excluded.title,
  short_description = excluded.short_description,
  long_description = excluded.long_description,
  updated_at_utc = excluded.updated_at_utc;

ALTER TABLE role_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflow_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflow_executions ENABLE ROW LEVEL SECURITY;

INSERT INTO schema_migrations (version, applied_at_utc, description)
VALUES (51, now()::text, 'add agent role normalization workflows')
ON CONFLICT (version) DO NOTHING;
