-- brai:reapply-after-production-seed
-- Acceptance reconcile migration 0027.

INSERT INTO activity_types (id, title, description, created_at_utc)
VALUES (
  'goal',
  'Цель',
  'Желаемый личный результат, для завершения которого требуется минимум два обязательных действия или операции.',
  now()::text
)
ON CONFLICT (id) DO UPDATE SET
  title = excluded.title,
  description = excluded.description;

DROP INDEX IF EXISTS idx_activities_raw_queue;
CREATE INDEX idx_activities_raw_queue
  ON activities (created_at_utc, id)
  WHERE item_roles_id IS NULL
    AND activity_type_id IN ('action', 'goal', 'operation');

UPDATE role_contracts
SET lifecycle_json = '{"statuses":["active","ended","deleted"],"raw_when":"activity_type_id in (''action'',''goal'',''operation'') and item_roles_id is null"}',
  updated_at_utc = now()::text
WHERE id = 'activity';

UPDATE agents
SET summary = 'Нормализует raw Activity типов action и goal в краткий title, description_md, reason и технический разбор с учетом будущих описаний вложений; operation поддерживается только для чтения legacy-записей.',
  input_description = 'activities.activity_type_id (action или goal; legacy operation только для чтения), title, description_md, optional image description, author, reason и status.',
  llm_prompt_template = 'Разбери Activity-запись на русском языке.
Activity может быть пользовательским действием action или личной целью goal.
Тип operation существует только для чтения legacy-данных. Не создавай и не предлагай новые Activity типа operation: новые Operations принадлежат Inbox.
Сохраняй исходное намерение, имена, названия и все важные ограничения.
Исправляй очевидные опечатки, но не меняй смысл.
Верни только JSON без Markdown с полями:
{"title":"короткий заголовок до 80 символов","description":"понятное описание действия или цели","reason":"почему эта activity существует, если причина понятна, иначе пустая строка","normalization":"технический разбор"}

Тип Activity:
{{activity_type}}

Заголовок:
{{title}}

Описание:
{{description}}

Описание вложений/изображений, если есть:
{{image_description}}

Автор:
{{author}}

Причина:
{{reason}}

Статус:
{{status}}',
  updated_at_utc = now()::text
WHERE id = 'activity.normalizer';

ALTER TABLE events DROP CONSTRAINT IF EXISTS events_event_domain_check;
ALTER TABLE events
  ADD CONSTRAINT events_event_domain_check
  CHECK (event_domain IN ('timer', 'activity', 'inbox', 'relation', 'system'));

INSERT INTO sequence_counters (name, last_value)
VALUES ('events.domain_sequence.relation', COALESCE((
  SELECT MAX(domain_sequence) FROM events WHERE event_domain = 'relation'
), 0))
ON CONFLICT (name) DO UPDATE SET
  last_value = GREATEST(sequence_counters.last_value, excluded.last_value);

CREATE TABLE IF NOT EXISTS relation_types (
  id text PRIMARY KEY,
  user_id text,
  key text NOT NULL,
  title text NOT NULL CHECK (length(title) BETWEEN 1 AND 200),
  description text NOT NULL DEFAULT '' CHECK (length(description) <= 8000),
  directionality text NOT NULL DEFAULT 'symmetric'
    CHECK (directionality IN ('symmetric', 'directed')),
  source_label text NOT NULL DEFAULT '' CHECK (length(source_label) <= 200),
  target_label text NOT NULL DEFAULT '' CHECK (length(target_label) <= 200),
  is_ordered integer NOT NULL DEFAULT 0 CHECK (is_ordered IN (0, 1)),
  status text NOT NULL DEFAULT 'candidate'
    CHECK (status IN ('candidate', 'active', 'retired')),
  is_system integer NOT NULL DEFAULT 0 CHECK (is_system IN (0, 1)),
  created_by_actor_type text NOT NULL
    CHECK (created_by_actor_type IN ('user', 'agent', 'system')),
  created_by_actor_id text,
  created_at_utc text NOT NULL,
  updated_at_utc text NOT NULL,
  retired_at_utc text,
  CHECK (
    (is_system = 1 AND user_id IS NULL)
    OR (is_system = 0 AND user_id IS NOT NULL)
  ),
  CHECK (
    (directionality = 'directed' AND length(btrim(source_label)) > 0 AND length(btrim(target_label)) > 0)
    OR (directionality = 'symmetric' AND source_label = '' AND target_label = '')
  ),
  CHECK (
    (status = 'retired' AND retired_at_utc IS NOT NULL)
    OR (status <> 'retired' AND retired_at_utc IS NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_relation_types_system_key
  ON relation_types (key)
  WHERE is_system = 1;
CREATE UNIQUE INDEX IF NOT EXISTS idx_relation_types_user_key
  ON relation_types (user_id, key)
  WHERE is_system = 0;
CREATE INDEX IF NOT EXISTS idx_relation_types_user_status
  ON relation_types (user_id, status, key);

CREATE TABLE IF NOT EXISTS relation_type_endpoint_rules (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relation_types_id text NOT NULL REFERENCES relation_types(id) ON DELETE RESTRICT,
  source_role_key text NOT NULL,
  source_type_key text NOT NULL,
  target_role_key text NOT NULL,
  target_type_key text NOT NULL,
  created_at_utc text NOT NULL,
  updated_at_utc text NOT NULL,
  UNIQUE (
    relation_types_id,
    source_role_key,
    source_type_key,
    target_role_key,
    target_type_key
  )
);

CREATE INDEX IF NOT EXISTS idx_relation_endpoint_rules_type
  ON relation_type_endpoint_rules (relation_types_id, source_role_key, target_role_key);

CREATE TABLE IF NOT EXISTS relations (
  id text PRIMARY KEY,
  user_id text NOT NULL,
  relation_types_id text NOT NULL REFERENCES relation_types(id) ON DELETE RESTRICT,
  source_items_id text NOT NULL REFERENCES items(id) ON DELETE RESTRICT,
  target_items_id text NOT NULL REFERENCES items(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'ended')),
  position integer CHECK (position IS NULL OR position >= 0),
  active_from_utc text NOT NULL,
  active_to_utc text,
  operation_id text NOT NULL,
  ended_operation_id text,
  origin_decision_id text,
  created_by_actor_type text NOT NULL
    CHECK (created_by_actor_type IN ('user', 'agent', 'system')),
  created_by_actor_id text,
  ended_by_actor_type text
    CHECK (ended_by_actor_type IS NULL OR ended_by_actor_type IN ('user', 'agent', 'system')),
  ended_by_actor_id text,
  end_reason text CHECK (end_reason IS NULL OR length(end_reason) <= 500),
  metadata_json text NOT NULL DEFAULT '{}'
    CHECK (length(metadata_json) <= 16000 AND jsonb_typeof(metadata_json::jsonb) = 'object'),
  created_at_utc text NOT NULL,
  updated_at_utc text NOT NULL,
  CHECK (source_items_id <> target_items_id),
  CHECK (
    (status = 'active' AND active_to_utc IS NULL AND ended_operation_id IS NULL AND ended_by_actor_type IS NULL AND end_reason IS NULL)
    OR (status = 'ended' AND active_to_utc IS NOT NULL AND ended_operation_id IS NOT NULL AND ended_by_actor_type IS NOT NULL AND end_reason IS NOT NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_relations_one_active_edge
  ON relations (user_id, relation_types_id, source_items_id, target_items_id)
  WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_relations_user_type_status
  ON relations (user_id, relation_types_id, status, updated_at_utc DESC, id);
CREATE INDEX IF NOT EXISTS idx_relations_user_source_active
  ON relations (user_id, source_items_id, relation_types_id)
  WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_relations_user_target_active
  ON relations (user_id, target_items_id, relation_types_id)
  WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_relations_target_position
  ON relations (user_id, relation_types_id, target_items_id, position, id)
  WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_relations_lifecycle_history
  ON relations (user_id, active_from_utc DESC, active_to_utc DESC, id);
CREATE INDEX IF NOT EXISTS idx_relations_operation
  ON relations (user_id, operation_id, created_at_utc, id);
CREATE INDEX IF NOT EXISTS idx_relations_origin_decision
  ON relations (origin_decision_id, created_at_utc, id)
  WHERE origin_decision_id IS NOT NULL;

INSERT INTO relation_types (
  id, user_id, key, title, description, directionality, source_label, target_label,
  is_ordered, status, is_system, created_by_actor_type, created_by_actor_id,
  created_at_utc, updated_at_utc, retired_at_utc
) VALUES (
  'part_of', NULL, 'part_of', 'Часть цели',
  'Направленная связь от Action или нормализованной Operation к следующей по уровню Goal.',
  'directed', 'является частью', 'содержит', 1, 'active', 1, 'system',
  'migration:62', now()::text, now()::text, NULL
)
ON CONFLICT (id) DO UPDATE SET
  user_id = NULL,
  key = excluded.key,
  title = excluded.title,
  description = excluded.description,
  directionality = excluded.directionality,
  source_label = excluded.source_label,
  target_label = excluded.target_label,
  is_ordered = excluded.is_ordered,
  status = excluded.status,
  is_system = excluded.is_system,
  updated_at_utc = excluded.updated_at_utc,
  retired_at_utc = NULL;

INSERT INTO relation_type_endpoint_rules (
  relation_types_id, source_role_key, source_type_key,
  target_role_key, target_type_key, created_at_utc, updated_at_utc
) VALUES
  ('part_of', 'activity', 'action', 'activity', 'goal', now()::text, now()::text),
  ('part_of', 'inbox', 'operation', 'activity', 'goal', now()::text, now()::text)
ON CONFLICT (
  relation_types_id,
  source_role_key,
  source_type_key,
  target_role_key,
  target_type_key
) DO UPDATE SET updated_at_utc = excluded.updated_at_utc;

ALTER TABLE relation_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE relation_type_endpoint_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE relations ENABLE ROW LEVEL SECURITY;

INSERT INTO table_descriptions (
  table_name, title, short_description, long_description, updated_at_utc
) VALUES
  (
    'relation_types',
    'Relation types',
    'Версионированные системные и пользовательские семантические типы Relations.',
    'Хранит ownership, stable key, directed/symmetric semantics, labels, ordering, lifecycle и actor provenance. System types принадлежат migrations; private types видимы только своему user.',
    now()::text
  ),
  (
    'relation_type_endpoint_rules',
    'Relation endpoint rules',
    'Queryable contracts допустимых role-domain и role-local типов endpoint.',
    'Rules используют stable role/type keys без SQL table names. V1 part_of допускает только activity/action -> activity/goal и inbox/operation -> activity/goal.',
    now()::text
  ),
  (
    'relations',
    'Relations',
    'Canonical binary temporal facts между Items одного пользователя.',
    'Хранит directed/canonicalized endpoints, active/ended interval, per-target position, operation/decision/actor provenance и bounded metadata. End сохраняет row; re-add создаёт новый interval.',
    now()::text
  ),
  (
    'events',
    'Global events',
    'Единственный canonical ledger timer, activity, inbox, relation и system событий.',
    'Accepted и ignored domain events используют global server sequence и domain-local revision. Relation domain хранит create/end/reorder outcomes и idempotency payload.',
    now()::text
  ),
  (
    'activities',
    'Activities',
    'Role table Actions и Goals с read-only поддержкой legacy Operations.',
    'Raw Activity action/goal не имеет item_roles_id; workflow activity.raw-normalization создает entity/role, связывает initial_event_id, обрабатывает будущие вложения и сохраняет compact execution state. Goal использует activity_type_id=goal и существующий Activity payload/role; отдельная Goal table или Goal role не создаётся. Legacy activities.operation доступен только для чтения: новые Operations принадлежат Inbox и здесь не создаются.',
    now()::text
  )
ON CONFLICT (table_name) DO UPDATE SET
  title = excluded.title,
  short_description = excluded.short_description,
  long_description = excluded.long_description,
  updated_at_utc = excluded.updated_at_utc;

INSERT INTO schema_migrations (version, applied_at_utc, description)
VALUES (63, now()::text, 'add Relations catalog, canonical facts, and Goal activity type')
ON CONFLICT (version) DO NOTHING;
