-- brai:reapply-after-production-seed
-- Work-scoped, evidence-backed version history.
CREATE TABLE IF NOT EXISTS release_works (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_key text NOT NULL UNIQUE,
  status text NOT NULL CHECK (status IN ('active', 'finalizing', 'finalized', 'cancelled')),
  created_at_utc text NOT NULL,
  updated_at_utc text NOT NULL,
  finalized_at_utc text,
  CHECK (
    (status = 'finalized' AND finalized_at_utc IS NOT NULL)
    OR (status <> 'finalized' AND finalized_at_utc IS NULL)
  )
);

CREATE TABLE IF NOT EXISTS github_pull_requests (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_works_id integer NOT NULL REFERENCES release_works(id) ON DELETE RESTRICT,
  work_role text NOT NULL CHECK (work_role IN ('owner', 'support')),
  repository text NOT NULL,
  pull_number integer NOT NULL CHECK (pull_number > 0),
  url text NOT NULL,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  author_login text NOT NULL,
  state text NOT NULL,
  is_draft boolean NOT NULL DEFAULT false,
  head_branch text NOT NULL,
  base_branch text NOT NULL,
  merge_commit_sha text,
  github_created_at_utc text NOT NULL,
  github_updated_at_utc text NOT NULL,
  github_closed_at_utc text,
  github_merged_at_utc text,
  created_at_utc text NOT NULL,
  updated_at_utc text NOT NULL,
  UNIQUE (repository, pull_number)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_github_pull_requests_one_owner_per_work
  ON github_pull_requests (release_works_id)
  WHERE work_role = 'owner';

ALTER TABLE build_versions
  ADD COLUMN IF NOT EXISTS release_works_id integer REFERENCES release_works(id) ON DELETE RESTRICT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_build_versions_work_type
  ON build_versions (release_works_id, version_type_id)
  WHERE release_works_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_build_versions_id_type
  ON build_versions (id, version_type_id);

CREATE TABLE IF NOT EXISTS build_version_details (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  build_versions_id integer NOT NULL REFERENCES build_versions(id) ON DELETE CASCADE,
  github_pull_requests_id integer REFERENCES github_pull_requests(id) ON DELETE SET NULL,
  title text NOT NULL CHECK (length(btrim(title)) > 0),
  description text NOT NULL CHECK (length(btrim(description)) > 0),
  display_order integer NOT NULL CHECK (display_order > 0),
  created_at_utc text NOT NULL,
  updated_at_utc text NOT NULL,
  UNIQUE (build_versions_id, display_order)
);

CREATE TABLE IF NOT EXISTS build_version_pull_requests (
  build_versions_id integer NOT NULL,
  version_type_id text NOT NULL REFERENCES version_types(id),
  github_pull_requests_id integer NOT NULL REFERENCES github_pull_requests(id) ON DELETE RESTRICT,
  created_at_utc text NOT NULL,
  PRIMARY KEY (build_versions_id, github_pull_requests_id),
  FOREIGN KEY (build_versions_id, version_type_id)
    REFERENCES build_versions(id, version_type_id) ON DELETE CASCADE,
  UNIQUE (github_pull_requests_id, version_type_id)
);

CREATE INDEX IF NOT EXISTS idx_release_works_status_updated
  ON release_works (status, updated_at_utc);
CREATE INDEX IF NOT EXISTS idx_github_pull_requests_work
  ON github_pull_requests (release_works_id, github_merged_at_utc, pull_number);
CREATE INDEX IF NOT EXISTS idx_build_versions_history
  ON build_versions (released_at_utc DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_build_versions_type_history
  ON build_versions (version_type_id, released_at_utc DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_build_version_details_parent
  ON build_version_details (build_versions_id, display_order);
CREATE INDEX IF NOT EXISTS idx_build_version_pull_requests_parent
  ON build_version_pull_requests (build_versions_id, version_type_id);

CREATE OR REPLACE FUNCTION reject_release_work_key_update()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NEW.work_key IS DISTINCT FROM OLD.work_key THEN
    RAISE EXCEPTION 'release_works.work_key is immutable';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_release_works_immutable_key ON release_works;
CREATE TRIGGER trg_release_works_immutable_key
BEFORE UPDATE OF work_key ON release_works
FOR EACH ROW EXECUTE FUNCTION reject_release_work_key_update();

ALTER TABLE release_works ENABLE ROW LEVEL SECURITY;
ALTER TABLE github_pull_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE build_version_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE build_version_pull_requests ENABLE ROW LEVEL SECURITY;

INSERT INTO version_types (id, title, description, created_at_utc) VALUES
  ('build', 'Product', 'Принятая версия продукта Brai с завершённым объёмом работы, независимо от web/OTA-версии приложения.', now()::text),
  ('apk', 'Android APK', 'Опубликованная версия Android APK. Увеличивается только при осознанном выпуске нового APK.', now()::text),
  ('macos', 'macOS', 'Тип зарезервирован для будущих релизов приложения Brai для macOS.', now()::text),
  ('ios', 'iOS', 'Тип зарезервирован для будущих релизов приложения Brai для iOS.', now()::text)
ON CONFLICT (id) DO UPDATE SET
  title = excluded.title,
  description = excluded.description;

INSERT INTO table_descriptions (table_name, title, short_description, long_description, updated_at_utc) VALUES
  ('version_types', 'Типы версий', 'Канонические линии Product и platform-версий.', 'Product и Android APK — активные линии; macOS и iOS зарезервированы без фиктивных версий и счётчиков.', now()::text),
  ('build_versions', 'Версии продукта и платформ', 'Нумерованный ledger принятых Product-изменений и опубликованных platform artifacts.', 'Build — внутренний id Product-линии; APK — Android APK. Типы macOS и iOS не получают строк до фактической публикации своих артефактов.', now()::text),
  ('build_version_counters', 'Счётчики версий', 'Следующие номера активных линий.', 'Счётчики создаются только для активных Product (build) и Android APK; для будущих macOS и iOS счётчиков пока нет.', now()::text),
  ('build_version_refs', 'Ссылки версий', 'Источник и целевая доставка версии.', 'Связывает work/platform version с исходной веткой и commit, а также с целевой веткой и commit доставки.', now()::text),
  ('release_works', 'Release works', 'Стабильные идентификаторы законченных объёмов работы.', 'Один work объединяет owner PR и необязательные support PR; build создаётся только при финализации всего work.', now()::text),
  ('github_pull_requests', 'GitHub pull requests', 'Публичные GitHub-снимки PR, зарегистрированных в release work.', 'Хранит полный release-time snapshot PR и неизменяемую принадлежность к work с ролью owner или support.', now()::text),
  ('build_version_details', 'Version details', 'Атомарные упорядоченные изменения версии.', 'Каждая версия содержит хотя бы одну независимую деталь; ссылка на PR сохраняет происхождение изменения.', now()::text),
  ('build_version_pull_requests', 'Version pull requests', 'Типизированные связи версий с GitHub PR.', 'Позволяет одному PR относиться к одному build и одному APK, но не к двум версиям одного типа.', now()::text)
ON CONFLICT (table_name) DO UPDATE SET
  title = excluded.title,
  short_description = excluded.short_description,
  long_description = excluded.long_description,
  updated_at_utc = excluded.updated_at_utc;

INSERT INTO schema_migrations (version, applied_at_utc, description)
VALUES (67, now()::text, 'normalize work-scoped version history')
ON CONFLICT (version) DO NOTHING;
